import os
import streamlit as st
from extractor import extract_text, extract_images
from ddr_generator import generate_ddr_report

st.set_page_config(page_title="AI DDR Report Generator", layout="wide")

st.title("AI DDR Report Generator")
st.markdown("Upload the **Inspection Report** and **Thermal Report** to generate a structured DDR report.")

EXTRACTED_IMAGE_DIR = "extracted_images"
OUTPUT_DIR = "sample_outputs"
os.makedirs(EXTRACTED_IMAGE_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)


def save_uploaded_file(uploaded_file, save_dir="."):
    file_path = os.path.join(save_dir, uploaded_file.name)
    with open(file_path, "wb") as f:
        f.write(uploaded_file.getbuffer())
    return file_path


inspection_file = st.file_uploader(
    "Upload Inspection Report (PDF/DOCX)",
    type=["pdf", "docx"],
    key="inspection"
)

thermal_file = st.file_uploader(
    "Upload Thermal Report (PDF/DOCX)",
    type=["pdf", "docx"],
    key="thermal"
)

if inspection_file and thermal_file:
    if st.button("Generate DDR Report"):
        try:
            with st.spinner("Processing files and generating DDR report..."):
                inspection_path = save_uploaded_file(inspection_file)
                thermal_path = save_uploaded_file(thermal_file)

                inspection_text = extract_text(inspection_path)
                thermal_text = extract_text(thermal_path)

                inspection_images = extract_images(
                    inspection_path,
                    EXTRACTED_IMAGE_DIR,
                    prefix="inspection"
                )

                thermal_images = extract_images(
                    thermal_path,
                    EXTRACTED_IMAGE_DIR,
                    prefix="thermal"
                )

                all_images = inspection_images + thermal_images

                ddr_report = generate_ddr_report(
                    inspection_text=inspection_text,
                    thermal_text=thermal_text,
                    image_paths=all_images
                )

                output_path = os.path.join(OUTPUT_DIR, "generated_ddr_report.md")
                with open(output_path, "w", encoding="utf-8") as f:
                    f.write(ddr_report)

                txt_output_path = os.path.join(OUTPUT_DIR, "generated_ddr_report.txt")
                with open(txt_output_path, "w", encoding="utf-8") as f:
                    f.write(ddr_report)

                st.success("DDR Report generated successfully!")

                col1, col2 = st.columns(2)

                with col1:
                    st.subheader("Inspection Report Extracted Text")
                    st.text_area("Inspection Text", inspection_text[:8000], height=300)

                with col2:
                    st.subheader("Thermal Report Extracted Text")
                    st.text_area("Thermal Text", thermal_text[:8000], height=300)

                st.subheader("Generated DDR Report")
                st.markdown(ddr_report)

                st.download_button(
                    label="Download DDR Report",
                    data=ddr_report,
                    file_name="generated_ddr_report.md",
                    mime="text/markdown"
                )

                if all_images:
                    st.subheader("Extracted Images")
                    for img_path in all_images:
                        st.image(img_path, caption=os.path.basename(img_path), width=300)
                else:
                    st.info("No images extracted from uploaded documents.")

                st.subheader("Submission Notes")
                st.write("This report was generated by combining observations from the Inspection Report and Thermal Report using an LLM-based workflow.")

        except Exception as e:
            st.error(f"Error: {str(e)}")